apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: snapp
data:
  management.endpoint.metrics.enabled: "true"
  spring.datasource.url: jdbc:mysql://mysql-headless:3306/snapp_demo?allowPublicKeyRetrieval=true&useSSL=false 
  spring.jpa.properties.hibernate.default_schema: snapp_demo
  spring.flyway.schemas: snapp_demo
