apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: snapp-app-hpa
  namespace: snapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snapp-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 25
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 300Mi