name: Build

# on:
#   workflow_call:
#     inputs:
#       new_version_app:
#         required: true
#         type: string
#     secrets:
#       docker_user:
#         required: true
#       docker_token:
#         required: true

on: workflow_dispatch

jobs:
  generate-tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: create tag from new version
        if: ${{ inputs.new_version_app }}
        id: tag
        run: |
          git tag "${{ inputs.new_version_app }}"
          git push origin "${{ inputs.new_version_app }}" --force

  build-artifact:
    if: ${{ inputs.new_version_app }}
    runs-on: ubuntu-latest
    needs: [generate-tag-version]
    steps:  
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: change application version in pom file
        uses: Mudlet/xmlstarlet-action@master
        with:
          args: ed -L -u /_:project/_:version -v ${{ inputs.new_version_app }} pom.xml
      - name: build jar file with skipTests
        run: mvn clean install --batch-mode -DskipTests
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: change jar file directory name 
        run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: snapp-app-${{ inputs.new_version_app }}
          path: staging/snapp-app-${{ inputs.new_version_app }}.jar

  build-image:
    if: ${{ inputs.new_version_app }}
    runs-on: ubuntu-latest
    needs: [build-artifact]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: snapp-app-${{ inputs.new_version_app }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_token }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ehsanmsb/snapp-app
          tags: |
            type=semver,pattern={{raw}},value=${{ inputs.new_version_app }}     
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            JAR_FILE=snapp-app-${{ inputs.new_version_app }}.jar
          tags: ${{ steps.meta.outputs.tags }}