name: First Workflow 

on:
  push:
    branches:
      - "main"

jobs:
  approved:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"