name: Git Version

on:
  push:
    branches:
      - "main"

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Application Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: true
          bump_each_commit_patch_pattern: ""
          search_commit_body: true
          user_format_type: "csv"
          enable_prerelease_mode: false
          debug: false

      - name: echo Version
        run: echo "${{ steps.version.outputs }}"

      - name: Tag Version
        if: steps.version.outputs.version_tag
        run: |
          git tag "${{ steps.version.outputs.version_tag }}"
          git push origin "${{ steps.version.outputs.version_tag }}" --force