name: Test

on:
  pull_request_review:
    types:
      - submitted
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: value
        run: |
          echo $GITHUB_BASE_REF
          echo $GITHUB_REF
          echo "${{ github.event.review.pull_request.head.ref }}""
          echo $GITHUB_REF_NAME
          echo $$RUNNER_OS