name: Test

on:
  pull_request_review:
    types:
      - submitted
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: value
        run: |
          echo "Review SHA: $GITHUB_SHA"
          echo "Review Ref: $GITHUB_REF"
          echo "Pull Request Ref: ${{ github.event.pull_request.head.ref }}"
          echo "Pull Request Name: ${{ github.event.pull_request.head.ref }}"
          echo "Runner OS: $RUNNER_OS"