name: Git Version

on:
  pull_request:
    types: [opened, reopened]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth:  --batch-mode -DskipTests
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'