name: Versioning

on:
  push:
    branches:
      - "main"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo value
        run: echo ${{ vars.NEW_VERSION_GENERATED }}
      - name: change value
        run: |
          echo "NEW_VERSION_GENERATED=v1.2.0" >> $GITHUB_ENV