name: Versioning

on:
  pull_request:
    types:
      - closed

jobs:
  versioning:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag.outputs.app_version }}    
    env:
      new_version_flag: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: new-version
        id: new-version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: true
          bump_each_commit_patch_pattern: "fix:"
          search_commit_body: true
          user_format_type: "csv"
          enable_prerelease_mode: false
          debug: false
      - name: change-pom-file
        uses: Mudlet/xmlstarlet-action@master
        with:
          args: ed -L -u /_:project/_:version -v ${{ steps.new-version.outputs.version_tag }} pom.xml
      - name: Commit-pom-file
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.SNAPP_REPO_TOKEN }}