name: Versioning

# on:
#   pull_request:
#     types:
#       - closed

on:
  push:
    branches:
      - "new-new"
jobs:
  versioning:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag.outputs.app_version }}    
    env:
      new_version_flag: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check commit message
        id: commit
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
          if [[ "$commit_message" == *"BREAKING CHANGE:"* || "$commit_message" == *"fix:"* || "$commit_message" == *"feat:"* ]]; then
            echo "new_version_flag=true" >> $GITHUB_ENV
            echo "Commit message contains conventional commits specification for create new version. Workflow will run."
          else
            echo "Commit message does not contain conventional commits specification. Workflow will be skipped."
          fi
      - name: new-version
        # if: env.new_version_flag == 'true'
        id: new-version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: true
          bump_each_commit_patch_pattern: "fix:"
          search_commit_body: true
          user_format_type: "csv"
          enable_prerelease_mode: false
          debug: false
      - name: change-pom-file
        uses: Mudlet/xmlstarlet-action@master
        with:
          args: ed -L -u /_:project/_:version -v ${{ steps.new-version.outputs.version_tag }} pom.xml
      - name: Commit-pom-file
        run: |
          git config --global user.name 'ehsan'
          git config --global user.email 'ehsan.mosayebi@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.SNAPP_REPO_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git commit -am "Automated Pom commit"
          git push
        # uses: actions-js/push@master
        # with:
        #   github_token: ${{ secrets.SNAPP_REPO_TOKEN }}
        #   branch: $GITHUB_REF_NAME
