name: Versioning

on:
  push:
    branches:
      - "main"

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install requirement
        run: sudo apt-get install libxml2-utils
      - name: Check version in pom file
        id: get-app-version
        run: |
          version=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
          echo "::set-output name=app_version::$version"
      - name: Check Latest Tag
        id: get-latest-tag
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "::set-output name=latest_tag::$latest_tag"
      - name: Compare versions
        id: comparison-version
        run: |
          version=${{ steps.get-app-version.outputs.app_version }}
          pom_version=${version#"v"}
          version=$${{ steps.get-latest-tag.outputs.latest_tag }}
          latest_tag=${version#"v"}
          IFS='.' read -r -a pom_version_parts <<< "$pom_version"
          IFS='.' read -r -a latest_tag_parts <<< "$latest_tag"
          if [[ "${latest_tag_parts[1]}" == "${latest_tag_parts[1]}" ]]; then
             test="Minor version is chnaged"
          elif [[ "${latest_tag_parts[2]}" != "${latest_tag_parts[2]}" ]]; then
            test="Patche version is chnaged"
          fi
          echo $test
  # call_build:
  #   if: github.event.pull_request.merged == true 
  #   needs: [generate_new_version]
  #   uses: ./.github/workflows/Build.yaml
  #   with:
  #     new_version_app: ${{ needs.generate_new_version.outputs.new_version }}  
  #   secrets:
  #     docker_user: ${{ secrets.DOCKERHUB_USERNAME }}
  #     docker_token: ${{ secrets.DOCKERHUB_TOKEN }}